<?xml version="1.0" encoding="utf-8"?>
<Database Name="match_analysis_pdm" Class="DataClassesMatchDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=PC3705-20090828\SQLEXPRESS;Initial Catalog=match_analysis_pdm;Integrated Security=True" SettingsObjectName="Soccer_Score_Forecast.Properties.Settings" SettingsPropertyName="match_analysis_pdmConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.live_Table" Member="live_Table">
    <Type Name="live_Table">
      <Column Name="live_table_id" Type="System.Decimal" DbType="Decimal(18,0) NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="html_position" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="home_team_big" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="away_team_big" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="match_type" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="s_date" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="s_time" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="status" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="home_team" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="away_team" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="full_time_score" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="half_time_score" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.live_Table_lib" Member="live_Table_lib">
    <Type Name="live_Table_lib">
      <Column Name="live_table_lib_id" Type="System.Decimal" DbType="Decimal(18,0) NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="html_position" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="home_team_big" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="away_team_big" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="match_type" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="match_time" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="status" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="home_team" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="away_team" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="home_red_card" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="away_red_card" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="full_home_goals" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="full_away_goals" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="half_home_goals" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="half_away_goals" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.match_analysis_collection" Member="match_analysis_collection">
    <Type Name="match_analysis_collection">
      <Column Name="analysis_collection_id" Type="System.Decimal" DbType="Decimal(18,0) NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="live_table_lib_id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="result_tb_lib_id" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.result_tb" Member="result_tb">
    <Type Name="result_tb">
      <Column Name="result_tb_id" Type="System.Decimal" DbType="Decimal(18,0) NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="html_position" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="home_team_big" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="away_team_big" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="match_type" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="s_date" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="s_time" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="home_team" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="away_team" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="full_time_score" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="half_time_score" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="odds" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="win_loss_big" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.result_tb_lib" Member="result_tb_lib">
    <Type Name="result_tb_lib">
      <Column Name="result_tb_lib_id" Type="System.Decimal" DbType="Decimal(18,0) NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="html_position" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="home_team_big" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="away_team_big" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="match_type" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="match_time" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="home_team" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="away_team" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="odds" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="win_loss_big" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="home_red_card" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="away_red_card" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="full_home_goals" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="full_away_goals" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="half_home_goals" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="half_away_goals" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.live_okoo" Member="live_okoo">
    <Type Name="live_okoo">
      <Column Name="live_okoo_id" Type="System.Decimal" DbType="Decimal(18,0) NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="value" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="LeagueName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="match_time" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="MatchOrder1_HomeName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="MatchOrder1_HandicapNumber" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="MatchOrder1_AwayName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ok_1_0" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ok_1_1" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ok_1_2" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="MatchInfo" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Match_1_Win" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Match_1_Drawn" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Match_1_Lost" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.match_table_xpath" Member="match_table_xpath">
    <Type Name="match_table_xpath">
      <Column Name="uri_host_id" Type="System.Decimal" DbType="Decimal(18,0) NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="uri_host" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="max_table_xpath" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="max_table_id_value" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="second_table_xpath" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="second_table_id_value" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="order_table_id" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.match_analysis_result" Member="match_analysis_result">
    <Type Name="match_analysis_result">
      <Column Name="analysis_result_id" Type="System.Decimal" DbType="Decimal(18,0) NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="live_table_lib_id" Type="System.Decimal" DbType="Decimal(18,0) NOT NULL" CanBeNull="false" />
      <Column Name="result_tb_lib_id" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="pre_algorithm" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="pre_match_count" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="home_w" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="home_d" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="home_l" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="home_goals" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="away_goals" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="fit_win_loss" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="fit_goals" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="fit_odd_even" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="result_fit" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="result_goals" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="result_wdl" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.live_Aibo" Member="live_Aibo">
    <Type Name="live_Aibo">
      <Column Name="live_Aibo_id" Type="System.Decimal" DbType="Decimal(18,0) NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="value" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="LeagueName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="match_time" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="MatchOrder1_HomeName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="MatchOrder1_HandicapNumber" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="MatchOrder1_AwayName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
</Database>