#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.1
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoccerScore.Compact.Linq
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	public partial class SoccerScoreCompact : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region 可扩展性方法定义
    partial void OnCreated();
    partial void Insertlive_Aibo(live_Aibo instance);
    partial void Updatelive_Aibo(live_Aibo instance);
    partial void Deletelive_Aibo(live_Aibo instance);
    partial void Insertlive_okoo(live_okoo instance);
    partial void Updatelive_okoo(live_okoo instance);
    partial void Deletelive_okoo(live_okoo instance);
    partial void Insertlive_Table(live_Table instance);
    partial void Updatelive_Table(live_Table instance);
    partial void Deletelive_Table(live_Table instance);
    partial void Insertlive_Table_lib(live_Table_lib instance);
    partial void Updatelive_Table_lib(live_Table_lib instance);
    partial void Deletelive_Table_lib(live_Table_lib instance);
    partial void Insertmatch_analysis_collection(match_analysis_collection instance);
    partial void Updatematch_analysis_collection(match_analysis_collection instance);
    partial void Deletematch_analysis_collection(match_analysis_collection instance);
    partial void Insertmatch_analysis_result(match_analysis_result instance);
    partial void Updatematch_analysis_result(match_analysis_result instance);
    partial void Deletematch_analysis_result(match_analysis_result instance);
    partial void Insertmatch_table_xpath(match_table_xpath instance);
    partial void Updatematch_table_xpath(match_table_xpath instance);
    partial void Deletematch_table_xpath(match_table_xpath instance);
    partial void Insertresult_tb(result_tb instance);
    partial void Updateresult_tb(result_tb instance);
    partial void Deleteresult_tb(result_tb instance);
    partial void Insertresult_tb_lib(result_tb_lib instance);
    partial void Updateresult_tb_lib(result_tb_lib instance);
    partial void Deleteresult_tb_lib(result_tb_lib instance);
    #endregion
		
		public SoccerScoreCompact(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public SoccerScoreCompact(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public SoccerScoreCompact(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public SoccerScoreCompact(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<live_Aibo> live_Aibo
		{
			get
			{
				return this.GetTable<live_Aibo>();
			}
		}
		
		public System.Data.Linq.Table<live_okoo> live_okoo
		{
			get
			{
				return this.GetTable<live_okoo>();
			}
		}
		
		public System.Data.Linq.Table<live_Table> live_Table
		{
			get
			{
				return this.GetTable<live_Table>();
			}
		}
		
		public System.Data.Linq.Table<live_Table_lib> live_Table_lib
		{
			get
			{
				return this.GetTable<live_Table_lib>();
			}
		}
		
		public System.Data.Linq.Table<match_analysis_collection> match_analysis_collection
		{
			get
			{
				return this.GetTable<match_analysis_collection>();
			}
		}
		
		public System.Data.Linq.Table<match_analysis_result> match_analysis_result
		{
			get
			{
				return this.GetTable<match_analysis_result>();
			}
		}
		
		public System.Data.Linq.Table<match_table_xpath> match_table_xpath
		{
			get
			{
				return this.GetTable<match_table_xpath>();
			}
		}
		
		public System.Data.Linq.Table<result_tb> result_tb
		{
			get
			{
				return this.GetTable<result_tb>();
			}
		}
		
		public System.Data.Linq.Table<result_tb_lib> result_tb_lib
		{
			get
			{
				return this.GetTable<result_tb_lib>();
			}
		}
		
		public System.Data.Linq.Table<Tt> Tt
		{
			get
			{
				return this.GetTable<Tt>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute()]
	public partial class live_Aibo : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private decimal _Live_Aibo_id;
		
		private string _Value;
		
		private string _LeagueName;
		
		private string _Match_time;
		
		private string _MatchOrder1_HomeName;
		
		private string _MatchOrder1_HandicapNumber;
		
		private string _MatchOrder1_AwayName;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onlive_Aibo_idChanging(decimal value);
    partial void Onlive_Aibo_idChanged();
    partial void OnvalueChanging(string value);
    partial void OnvalueChanged();
    partial void OnLeagueNameChanging(string value);
    partial void OnLeagueNameChanged();
    partial void Onmatch_timeChanging(string value);
    partial void Onmatch_timeChanged();
    partial void OnMatchOrder1_HomeNameChanging(string value);
    partial void OnMatchOrder1_HomeNameChanged();
    partial void OnMatchOrder1_HandicapNumberChanging(string value);
    partial void OnMatchOrder1_HandicapNumberChanged();
    partial void OnMatchOrder1_AwayNameChanging(string value);
    partial void OnMatchOrder1_AwayNameChanged();
    #endregion
		
		public live_Aibo()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Live_Aibo_id", DbType="Decimal(18,0) NOT NULL", IsPrimaryKey=true)]
		public decimal live_Aibo_id
		{
			get
			{
				return this._Live_Aibo_id;
			}
			set
			{
				if ((this._Live_Aibo_id != value))
				{
					this.Onlive_Aibo_idChanging(value);
					this.SendPropertyChanging();
					this._Live_Aibo_id = value;
					this.SendPropertyChanged("live_Aibo_id");
					this.Onlive_Aibo_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Value", DbType="NVarChar(50)")]
		public string value
		{
			get
			{
				return this._Value;
			}
			set
			{
				if ((this._Value != value))
				{
					this.OnvalueChanging(value);
					this.SendPropertyChanging();
					this._Value = value;
					this.SendPropertyChanged("value");
					this.OnvalueChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LeagueName", DbType="NVarChar(50)")]
		public string LeagueName
		{
			get
			{
				return this._LeagueName;
			}
			set
			{
				if ((this._LeagueName != value))
				{
					this.OnLeagueNameChanging(value);
					this.SendPropertyChanging();
					this._LeagueName = value;
					this.SendPropertyChanged("LeagueName");
					this.OnLeagueNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Match_time", DbType="NVarChar(50)")]
		public string match_time
		{
			get
			{
				return this._Match_time;
			}
			set
			{
				if ((this._Match_time != value))
				{
					this.Onmatch_timeChanging(value);
					this.SendPropertyChanging();
					this._Match_time = value;
					this.SendPropertyChanged("match_time");
					this.Onmatch_timeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MatchOrder1_HomeName", DbType="NVarChar(50)")]
		public string MatchOrder1_HomeName
		{
			get
			{
				return this._MatchOrder1_HomeName;
			}
			set
			{
				if ((this._MatchOrder1_HomeName != value))
				{
					this.OnMatchOrder1_HomeNameChanging(value);
					this.SendPropertyChanging();
					this._MatchOrder1_HomeName = value;
					this.SendPropertyChanged("MatchOrder1_HomeName");
					this.OnMatchOrder1_HomeNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MatchOrder1_HandicapNumber", DbType="NVarChar(50)")]
		public string MatchOrder1_HandicapNumber
		{
			get
			{
				return this._MatchOrder1_HandicapNumber;
			}
			set
			{
				if ((this._MatchOrder1_HandicapNumber != value))
				{
					this.OnMatchOrder1_HandicapNumberChanging(value);
					this.SendPropertyChanging();
					this._MatchOrder1_HandicapNumber = value;
					this.SendPropertyChanged("MatchOrder1_HandicapNumber");
					this.OnMatchOrder1_HandicapNumberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MatchOrder1_AwayName", DbType="NVarChar(50)")]
		public string MatchOrder1_AwayName
		{
			get
			{
				return this._MatchOrder1_AwayName;
			}
			set
			{
				if ((this._MatchOrder1_AwayName != value))
				{
					this.OnMatchOrder1_AwayNameChanging(value);
					this.SendPropertyChanging();
					this._MatchOrder1_AwayName = value;
					this.SendPropertyChanged("MatchOrder1_AwayName");
					this.OnMatchOrder1_AwayNameChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute()]
	public partial class live_okoo : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private decimal _live_okoo_id;
		
		private System.Nullable<int> _value;
		
		private string _LeagueName;
		
		private string _match_time;
		
		private string _MatchOrder1_HomeName;
		
		private string _MatchOrder1_HandicapNumber;
		
		private string _MatchOrder1_AwayName;
		
		private string _ok_1_0;
		
		private string _ok_1_1;
		
		private string _ok_1_2;
		
		private string _MatchInfo;
		
		private string _Match_1_Win;
		
		private string _Match_1_Drawn;
		
		private string _Match_1_Lost;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onlive_okoo_idChanging(decimal value);
    partial void Onlive_okoo_idChanged();
    partial void OnvalueChanging(System.Nullable<int> value);
    partial void OnvalueChanged();
    partial void OnLeagueNameChanging(string value);
    partial void OnLeagueNameChanged();
    partial void Onmatch_timeChanging(string value);
    partial void Onmatch_timeChanged();
    partial void OnMatchOrder1_HomeNameChanging(string value);
    partial void OnMatchOrder1_HomeNameChanged();
    partial void OnMatchOrder1_HandicapNumberChanging(string value);
    partial void OnMatchOrder1_HandicapNumberChanged();
    partial void OnMatchOrder1_AwayNameChanging(string value);
    partial void OnMatchOrder1_AwayNameChanged();
    partial void Onok_1_0Changing(string value);
    partial void Onok_1_0Changed();
    partial void Onok_1_1Changing(string value);
    partial void Onok_1_1Changed();
    partial void Onok_1_2Changing(string value);
    partial void Onok_1_2Changed();
    partial void OnMatchInfoChanging(string value);
    partial void OnMatchInfoChanged();
    partial void OnMatch_1_WinChanging(string value);
    partial void OnMatch_1_WinChanged();
    partial void OnMatch_1_DrawnChanging(string value);
    partial void OnMatch_1_DrawnChanged();
    partial void OnMatch_1_LostChanging(string value);
    partial void OnMatch_1_LostChanged();
    #endregion
		
		public live_okoo()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_live_okoo_id", DbType="Decimal(18,0) NOT NULL", IsPrimaryKey=true)]
		public decimal live_okoo_id
		{
			get
			{
				return this._live_okoo_id;
			}
			set
			{
				if ((this._live_okoo_id != value))
				{
					this.Onlive_okoo_idChanging(value);
					this.SendPropertyChanging();
					this._live_okoo_id = value;
					this.SendPropertyChanged("live_okoo_id");
					this.Onlive_okoo_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_value", DbType="Int")]
		public System.Nullable<int> value
		{
			get
			{
				return this._value;
			}
			set
			{
				if ((this._value != value))
				{
					this.OnvalueChanging(value);
					this.SendPropertyChanging();
					this._value = value;
					this.SendPropertyChanged("value");
					this.OnvalueChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LeagueName", DbType="NVarChar(50)")]
		public string LeagueName
		{
			get
			{
				return this._LeagueName;
			}
			set
			{
				if ((this._LeagueName != value))
				{
					this.OnLeagueNameChanging(value);
					this.SendPropertyChanging();
					this._LeagueName = value;
					this.SendPropertyChanged("LeagueName");
					this.OnLeagueNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_match_time", DbType="NVarChar(50)")]
		public string match_time
		{
			get
			{
				return this._match_time;
			}
			set
			{
				if ((this._match_time != value))
				{
					this.Onmatch_timeChanging(value);
					this.SendPropertyChanging();
					this._match_time = value;
					this.SendPropertyChanged("match_time");
					this.Onmatch_timeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MatchOrder1_HomeName", DbType="NVarChar(50)")]
		public string MatchOrder1_HomeName
		{
			get
			{
				return this._MatchOrder1_HomeName;
			}
			set
			{
				if ((this._MatchOrder1_HomeName != value))
				{
					this.OnMatchOrder1_HomeNameChanging(value);
					this.SendPropertyChanging();
					this._MatchOrder1_HomeName = value;
					this.SendPropertyChanged("MatchOrder1_HomeName");
					this.OnMatchOrder1_HomeNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MatchOrder1_HandicapNumber", DbType="NVarChar(50)")]
		public string MatchOrder1_HandicapNumber
		{
			get
			{
				return this._MatchOrder1_HandicapNumber;
			}
			set
			{
				if ((this._MatchOrder1_HandicapNumber != value))
				{
					this.OnMatchOrder1_HandicapNumberChanging(value);
					this.SendPropertyChanging();
					this._MatchOrder1_HandicapNumber = value;
					this.SendPropertyChanged("MatchOrder1_HandicapNumber");
					this.OnMatchOrder1_HandicapNumberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MatchOrder1_AwayName", DbType="NVarChar(50)")]
		public string MatchOrder1_AwayName
		{
			get
			{
				return this._MatchOrder1_AwayName;
			}
			set
			{
				if ((this._MatchOrder1_AwayName != value))
				{
					this.OnMatchOrder1_AwayNameChanging(value);
					this.SendPropertyChanging();
					this._MatchOrder1_AwayName = value;
					this.SendPropertyChanged("MatchOrder1_AwayName");
					this.OnMatchOrder1_AwayNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ok_1_0", DbType="NVarChar(50)")]
		public string ok_1_0
		{
			get
			{
				return this._ok_1_0;
			}
			set
			{
				if ((this._ok_1_0 != value))
				{
					this.Onok_1_0Changing(value);
					this.SendPropertyChanging();
					this._ok_1_0 = value;
					this.SendPropertyChanged("ok_1_0");
					this.Onok_1_0Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ok_1_1", DbType="NVarChar(50)")]
		public string ok_1_1
		{
			get
			{
				return this._ok_1_1;
			}
			set
			{
				if ((this._ok_1_1 != value))
				{
					this.Onok_1_1Changing(value);
					this.SendPropertyChanging();
					this._ok_1_1 = value;
					this.SendPropertyChanged("ok_1_1");
					this.Onok_1_1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ok_1_2", DbType="NVarChar(50)")]
		public string ok_1_2
		{
			get
			{
				return this._ok_1_2;
			}
			set
			{
				if ((this._ok_1_2 != value))
				{
					this.Onok_1_2Changing(value);
					this.SendPropertyChanging();
					this._ok_1_2 = value;
					this.SendPropertyChanged("ok_1_2");
					this.Onok_1_2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MatchInfo", DbType="NVarChar(50)")]
		public string MatchInfo
		{
			get
			{
				return this._MatchInfo;
			}
			set
			{
				if ((this._MatchInfo != value))
				{
					this.OnMatchInfoChanging(value);
					this.SendPropertyChanging();
					this._MatchInfo = value;
					this.SendPropertyChanged("MatchInfo");
					this.OnMatchInfoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Match_1_Win", DbType="NVarChar(50)")]
		public string Match_1_Win
		{
			get
			{
				return this._Match_1_Win;
			}
			set
			{
				if ((this._Match_1_Win != value))
				{
					this.OnMatch_1_WinChanging(value);
					this.SendPropertyChanging();
					this._Match_1_Win = value;
					this.SendPropertyChanged("Match_1_Win");
					this.OnMatch_1_WinChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Match_1_Drawn", DbType="NVarChar(50)")]
		public string Match_1_Drawn
		{
			get
			{
				return this._Match_1_Drawn;
			}
			set
			{
				if ((this._Match_1_Drawn != value))
				{
					this.OnMatch_1_DrawnChanging(value);
					this.SendPropertyChanging();
					this._Match_1_Drawn = value;
					this.SendPropertyChanged("Match_1_Drawn");
					this.OnMatch_1_DrawnChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Match_1_Lost", DbType="NVarChar(50)")]
		public string Match_1_Lost
		{
			get
			{
				return this._Match_1_Lost;
			}
			set
			{
				if ((this._Match_1_Lost != value))
				{
					this.OnMatch_1_LostChanging(value);
					this.SendPropertyChanging();
					this._Match_1_Lost = value;
					this.SendPropertyChanged("Match_1_Lost");
					this.OnMatch_1_LostChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute()]
	public partial class live_Table : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private decimal _live_table_id;
		
		private string _html_position;
		
		private string _home_team_big;
		
		private string _away_team_big;
		
		private string _match_type;
		
		private string _s_date;
		
		private string _s_time;
		
		private string _status;
		
		private string _home_team;
		
		private string _away_team;
		
		private string _full_time_score;
		
		private string _half_time_score;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onlive_table_idChanging(decimal value);
    partial void Onlive_table_idChanged();
    partial void Onhtml_positionChanging(string value);
    partial void Onhtml_positionChanged();
    partial void Onhome_team_bigChanging(string value);
    partial void Onhome_team_bigChanged();
    partial void Onaway_team_bigChanging(string value);
    partial void Onaway_team_bigChanged();
    partial void Onmatch_typeChanging(string value);
    partial void Onmatch_typeChanged();
    partial void Ons_dateChanging(string value);
    partial void Ons_dateChanged();
    partial void Ons_timeChanging(string value);
    partial void Ons_timeChanged();
    partial void OnstatusChanging(string value);
    partial void OnstatusChanged();
    partial void Onhome_teamChanging(string value);
    partial void Onhome_teamChanged();
    partial void Onaway_teamChanging(string value);
    partial void Onaway_teamChanged();
    partial void Onfull_time_scoreChanging(string value);
    partial void Onfull_time_scoreChanged();
    partial void Onhalf_time_scoreChanging(string value);
    partial void Onhalf_time_scoreChanged();
    #endregion
		
		public live_Table()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_live_table_id", DbType="Decimal(18,0) NOT NULL", IsPrimaryKey=true)]
		public decimal live_table_id
		{
			get
			{
				return this._live_table_id;
			}
			set
			{
				if ((this._live_table_id != value))
				{
					this.Onlive_table_idChanging(value);
					this.SendPropertyChanging();
					this._live_table_id = value;
					this.SendPropertyChanged("live_table_id");
					this.Onlive_table_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_html_position", DbType="NVarChar(50)")]
		public string html_position
		{
			get
			{
				return this._html_position;
			}
			set
			{
				if ((this._html_position != value))
				{
					this.Onhtml_positionChanging(value);
					this.SendPropertyChanging();
					this._html_position = value;
					this.SendPropertyChanged("html_position");
					this.Onhtml_positionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_home_team_big", DbType="NVarChar(50)")]
		public string home_team_big
		{
			get
			{
				return this._home_team_big;
			}
			set
			{
				if ((this._home_team_big != value))
				{
					this.Onhome_team_bigChanging(value);
					this.SendPropertyChanging();
					this._home_team_big = value;
					this.SendPropertyChanged("home_team_big");
					this.Onhome_team_bigChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_away_team_big", DbType="NVarChar(50)")]
		public string away_team_big
		{
			get
			{
				return this._away_team_big;
			}
			set
			{
				if ((this._away_team_big != value))
				{
					this.Onaway_team_bigChanging(value);
					this.SendPropertyChanging();
					this._away_team_big = value;
					this.SendPropertyChanged("away_team_big");
					this.Onaway_team_bigChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_match_type", DbType="NVarChar(50)")]
		public string match_type
		{
			get
			{
				return this._match_type;
			}
			set
			{
				if ((this._match_type != value))
				{
					this.Onmatch_typeChanging(value);
					this.SendPropertyChanging();
					this._match_type = value;
					this.SendPropertyChanged("match_type");
					this.Onmatch_typeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_s_date", DbType="NVarChar(50)")]
		public string s_date
		{
			get
			{
				return this._s_date;
			}
			set
			{
				if ((this._s_date != value))
				{
					this.Ons_dateChanging(value);
					this.SendPropertyChanging();
					this._s_date = value;
					this.SendPropertyChanged("s_date");
					this.Ons_dateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_s_time", DbType="NVarChar(50)")]
		public string s_time
		{
			get
			{
				return this._s_time;
			}
			set
			{
				if ((this._s_time != value))
				{
					this.Ons_timeChanging(value);
					this.SendPropertyChanging();
					this._s_time = value;
					this.SendPropertyChanged("s_time");
					this.Ons_timeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_status", DbType="NVarChar(50)")]
		public string status
		{
			get
			{
				return this._status;
			}
			set
			{
				if ((this._status != value))
				{
					this.OnstatusChanging(value);
					this.SendPropertyChanging();
					this._status = value;
					this.SendPropertyChanged("status");
					this.OnstatusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_home_team", DbType="NVarChar(50)")]
		public string home_team
		{
			get
			{
				return this._home_team;
			}
			set
			{
				if ((this._home_team != value))
				{
					this.Onhome_teamChanging(value);
					this.SendPropertyChanging();
					this._home_team = value;
					this.SendPropertyChanged("home_team");
					this.Onhome_teamChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_away_team", DbType="NVarChar(50)")]
		public string away_team
		{
			get
			{
				return this._away_team;
			}
			set
			{
				if ((this._away_team != value))
				{
					this.Onaway_teamChanging(value);
					this.SendPropertyChanging();
					this._away_team = value;
					this.SendPropertyChanged("away_team");
					this.Onaway_teamChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_full_time_score", DbType="NVarChar(50)")]
		public string full_time_score
		{
			get
			{
				return this._full_time_score;
			}
			set
			{
				if ((this._full_time_score != value))
				{
					this.Onfull_time_scoreChanging(value);
					this.SendPropertyChanging();
					this._full_time_score = value;
					this.SendPropertyChanged("full_time_score");
					this.Onfull_time_scoreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_half_time_score", DbType="NVarChar(50)")]
		public string half_time_score
		{
			get
			{
				return this._half_time_score;
			}
			set
			{
				if ((this._half_time_score != value))
				{
					this.Onhalf_time_scoreChanging(value);
					this.SendPropertyChanging();
					this._half_time_score = value;
					this.SendPropertyChanged("half_time_score");
					this.Onhalf_time_scoreChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute()]
	public partial class live_Table_lib : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private decimal _live_table_lib_id;
		
		private System.Nullable<int> _html_position;
		
		private System.Nullable<int> _home_team_big;
		
		private System.Nullable<int> _away_team_big;
		
		private string _match_type;
		
		private System.Nullable<System.DateTime> _match_time;
		
		private string _status;
		
		private string _home_team;
		
		private string _away_team;
		
		private System.Nullable<int> _home_red_card;
		
		private System.Nullable<int> _away_red_card;
		
		private System.Nullable<int> _full_home_goals;
		
		private System.Nullable<int> _full_away_goals;
		
		private System.Nullable<int> _half_home_goals;
		
		private System.Nullable<int> _half_away_goals;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onlive_table_lib_idChanging(decimal value);
    partial void Onlive_table_lib_idChanged();
    partial void Onhtml_positionChanging(System.Nullable<int> value);
    partial void Onhtml_positionChanged();
    partial void Onhome_team_bigChanging(System.Nullable<int> value);
    partial void Onhome_team_bigChanged();
    partial void Onaway_team_bigChanging(System.Nullable<int> value);
    partial void Onaway_team_bigChanged();
    partial void Onmatch_typeChanging(string value);
    partial void Onmatch_typeChanged();
    partial void Onmatch_timeChanging(System.Nullable<System.DateTime> value);
    partial void Onmatch_timeChanged();
    partial void OnstatusChanging(string value);
    partial void OnstatusChanged();
    partial void Onhome_teamChanging(string value);
    partial void Onhome_teamChanged();
    partial void Onaway_teamChanging(string value);
    partial void Onaway_teamChanged();
    partial void Onhome_red_cardChanging(System.Nullable<int> value);
    partial void Onhome_red_cardChanged();
    partial void Onaway_red_cardChanging(System.Nullable<int> value);
    partial void Onaway_red_cardChanged();
    partial void Onfull_home_goalsChanging(System.Nullable<int> value);
    partial void Onfull_home_goalsChanged();
    partial void Onfull_away_goalsChanging(System.Nullable<int> value);
    partial void Onfull_away_goalsChanged();
    partial void Onhalf_home_goalsChanging(System.Nullable<int> value);
    partial void Onhalf_home_goalsChanged();
    partial void Onhalf_away_goalsChanging(System.Nullable<int> value);
    partial void Onhalf_away_goalsChanged();
    #endregion
		
		public live_Table_lib()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_live_table_lib_id", DbType="Decimal(18,0) NOT NULL", IsPrimaryKey=true)]
		public decimal live_table_lib_id
		{
			get
			{
				return this._live_table_lib_id;
			}
			set
			{
				if ((this._live_table_lib_id != value))
				{
					this.Onlive_table_lib_idChanging(value);
					this.SendPropertyChanging();
					this._live_table_lib_id = value;
					this.SendPropertyChanged("live_table_lib_id");
					this.Onlive_table_lib_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_html_position", DbType="Int")]
		public System.Nullable<int> html_position
		{
			get
			{
				return this._html_position;
			}
			set
			{
				if ((this._html_position != value))
				{
					this.Onhtml_positionChanging(value);
					this.SendPropertyChanging();
					this._html_position = value;
					this.SendPropertyChanged("html_position");
					this.Onhtml_positionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_home_team_big", DbType="Int")]
		public System.Nullable<int> home_team_big
		{
			get
			{
				return this._home_team_big;
			}
			set
			{
				if ((this._home_team_big != value))
				{
					this.Onhome_team_bigChanging(value);
					this.SendPropertyChanging();
					this._home_team_big = value;
					this.SendPropertyChanged("home_team_big");
					this.Onhome_team_bigChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_away_team_big", DbType="Int")]
		public System.Nullable<int> away_team_big
		{
			get
			{
				return this._away_team_big;
			}
			set
			{
				if ((this._away_team_big != value))
				{
					this.Onaway_team_bigChanging(value);
					this.SendPropertyChanging();
					this._away_team_big = value;
					this.SendPropertyChanged("away_team_big");
					this.Onaway_team_bigChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_match_type", DbType="NVarChar(50)")]
		public string match_type
		{
			get
			{
				return this._match_type;
			}
			set
			{
				if ((this._match_type != value))
				{
					this.Onmatch_typeChanging(value);
					this.SendPropertyChanging();
					this._match_type = value;
					this.SendPropertyChanged("match_type");
					this.Onmatch_typeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_match_time", DbType="DateTime")]
		public System.Nullable<System.DateTime> match_time
		{
			get
			{
				return this._match_time;
			}
			set
			{
				if ((this._match_time != value))
				{
					this.Onmatch_timeChanging(value);
					this.SendPropertyChanging();
					this._match_time = value;
					this.SendPropertyChanged("match_time");
					this.Onmatch_timeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_status", DbType="NVarChar(50)")]
		public string status
		{
			get
			{
				return this._status;
			}
			set
			{
				if ((this._status != value))
				{
					this.OnstatusChanging(value);
					this.SendPropertyChanging();
					this._status = value;
					this.SendPropertyChanged("status");
					this.OnstatusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_home_team", DbType="NVarChar(50)")]
		public string home_team
		{
			get
			{
				return this._home_team;
			}
			set
			{
				if ((this._home_team != value))
				{
					this.Onhome_teamChanging(value);
					this.SendPropertyChanging();
					this._home_team = value;
					this.SendPropertyChanged("home_team");
					this.Onhome_teamChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_away_team", DbType="NVarChar(50)")]
		public string away_team
		{
			get
			{
				return this._away_team;
			}
			set
			{
				if ((this._away_team != value))
				{
					this.Onaway_teamChanging(value);
					this.SendPropertyChanging();
					this._away_team = value;
					this.SendPropertyChanged("away_team");
					this.Onaway_teamChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_home_red_card", DbType="Int")]
		public System.Nullable<int> home_red_card
		{
			get
			{
				return this._home_red_card;
			}
			set
			{
				if ((this._home_red_card != value))
				{
					this.Onhome_red_cardChanging(value);
					this.SendPropertyChanging();
					this._home_red_card = value;
					this.SendPropertyChanged("home_red_card");
					this.Onhome_red_cardChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_away_red_card", DbType="Int")]
		public System.Nullable<int> away_red_card
		{
			get
			{
				return this._away_red_card;
			}
			set
			{
				if ((this._away_red_card != value))
				{
					this.Onaway_red_cardChanging(value);
					this.SendPropertyChanging();
					this._away_red_card = value;
					this.SendPropertyChanged("away_red_card");
					this.Onaway_red_cardChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_full_home_goals", DbType="Int")]
		public System.Nullable<int> full_home_goals
		{
			get
			{
				return this._full_home_goals;
			}
			set
			{
				if ((this._full_home_goals != value))
				{
					this.Onfull_home_goalsChanging(value);
					this.SendPropertyChanging();
					this._full_home_goals = value;
					this.SendPropertyChanged("full_home_goals");
					this.Onfull_home_goalsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_full_away_goals", DbType="Int")]
		public System.Nullable<int> full_away_goals
		{
			get
			{
				return this._full_away_goals;
			}
			set
			{
				if ((this._full_away_goals != value))
				{
					this.Onfull_away_goalsChanging(value);
					this.SendPropertyChanging();
					this._full_away_goals = value;
					this.SendPropertyChanged("full_away_goals");
					this.Onfull_away_goalsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_half_home_goals", DbType="Int")]
		public System.Nullable<int> half_home_goals
		{
			get
			{
				return this._half_home_goals;
			}
			set
			{
				if ((this._half_home_goals != value))
				{
					this.Onhalf_home_goalsChanging(value);
					this.SendPropertyChanging();
					this._half_home_goals = value;
					this.SendPropertyChanged("half_home_goals");
					this.Onhalf_home_goalsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_half_away_goals", DbType="Int")]
		public System.Nullable<int> half_away_goals
		{
			get
			{
				return this._half_away_goals;
			}
			set
			{
				if ((this._half_away_goals != value))
				{
					this.Onhalf_away_goalsChanging(value);
					this.SendPropertyChanging();
					this._half_away_goals = value;
					this.SendPropertyChanged("half_away_goals");
					this.Onhalf_away_goalsChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute()]
	public partial class match_analysis_collection : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private decimal _analysis_collection_id;
		
		private System.Nullable<int> _live_table_lib_id;
		
		private System.Nullable<int> _result_tb_lib_id;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onanalysis_collection_idChanging(decimal value);
    partial void Onanalysis_collection_idChanged();
    partial void Onlive_table_lib_idChanging(System.Nullable<int> value);
    partial void Onlive_table_lib_idChanged();
    partial void Onresult_tb_lib_idChanging(System.Nullable<int> value);
    partial void Onresult_tb_lib_idChanged();
    #endregion
		
		public match_analysis_collection()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_analysis_collection_id", DbType="Decimal(18,0) NOT NULL", IsPrimaryKey=true)]
		public decimal analysis_collection_id
		{
			get
			{
				return this._analysis_collection_id;
			}
			set
			{
				if ((this._analysis_collection_id != value))
				{
					this.Onanalysis_collection_idChanging(value);
					this.SendPropertyChanging();
					this._analysis_collection_id = value;
					this.SendPropertyChanged("analysis_collection_id");
					this.Onanalysis_collection_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_live_table_lib_id", DbType="Int")]
		public System.Nullable<int> live_table_lib_id
		{
			get
			{
				return this._live_table_lib_id;
			}
			set
			{
				if ((this._live_table_lib_id != value))
				{
					this.Onlive_table_lib_idChanging(value);
					this.SendPropertyChanging();
					this._live_table_lib_id = value;
					this.SendPropertyChanged("live_table_lib_id");
					this.Onlive_table_lib_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_result_tb_lib_id", DbType="Int")]
		public System.Nullable<int> result_tb_lib_id
		{
			get
			{
				return this._result_tb_lib_id;
			}
			set
			{
				if ((this._result_tb_lib_id != value))
				{
					this.Onresult_tb_lib_idChanging(value);
					this.SendPropertyChanging();
					this._result_tb_lib_id = value;
					this.SendPropertyChanged("result_tb_lib_id");
					this.Onresult_tb_lib_idChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute()]
	public partial class match_analysis_result : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private decimal _analysis_result_id;
		
		private decimal _live_table_lib_id;
		
		private System.Nullable<decimal> _result_tb_lib_id;
		
		private string _pre_algorithm;
		
		private System.Nullable<int> _pre_match_count;
		
		private System.Nullable<int> _home_w;
		
		private System.Nullable<int> _home_d;
		
		private System.Nullable<int> _home_l;
		
		private System.Nullable<double> _home_goals;
		
		private System.Nullable<double> _away_goals;
		
		private System.Nullable<double> _fit_win_loss;
		
		private System.Nullable<double> _fit_goals;
		
		private System.Nullable<double> _fit_odd_even;
		
		private string _result_fit;
		
		private string _result_goals;
		
		private string _result_wdl;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onanalysis_result_idChanging(decimal value);
    partial void Onanalysis_result_idChanged();
    partial void Onlive_table_lib_idChanging(decimal value);
    partial void Onlive_table_lib_idChanged();
    partial void Onresult_tb_lib_idChanging(System.Nullable<decimal> value);
    partial void Onresult_tb_lib_idChanged();
    partial void Onpre_algorithmChanging(string value);
    partial void Onpre_algorithmChanged();
    partial void Onpre_match_countChanging(System.Nullable<int> value);
    partial void Onpre_match_countChanged();
    partial void Onhome_wChanging(System.Nullable<int> value);
    partial void Onhome_wChanged();
    partial void Onhome_dChanging(System.Nullable<int> value);
    partial void Onhome_dChanged();
    partial void Onhome_lChanging(System.Nullable<int> value);
    partial void Onhome_lChanged();
    partial void Onhome_goalsChanging(System.Nullable<double> value);
    partial void Onhome_goalsChanged();
    partial void Onaway_goalsChanging(System.Nullable<double> value);
    partial void Onaway_goalsChanged();
    partial void Onfit_win_lossChanging(System.Nullable<double> value);
    partial void Onfit_win_lossChanged();
    partial void Onfit_goalsChanging(System.Nullable<double> value);
    partial void Onfit_goalsChanged();
    partial void Onfit_odd_evenChanging(System.Nullable<double> value);
    partial void Onfit_odd_evenChanged();
    partial void Onresult_fitChanging(string value);
    partial void Onresult_fitChanged();
    partial void Onresult_goalsChanging(string value);
    partial void Onresult_goalsChanged();
    partial void Onresult_wdlChanging(string value);
    partial void Onresult_wdlChanged();
    #endregion
		
		public match_analysis_result()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_analysis_result_id", DbType="Decimal(18,0) NOT NULL", IsPrimaryKey=true)]
		public decimal analysis_result_id
		{
			get
			{
				return this._analysis_result_id;
			}
			set
			{
				if ((this._analysis_result_id != value))
				{
					this.Onanalysis_result_idChanging(value);
					this.SendPropertyChanging();
					this._analysis_result_id = value;
					this.SendPropertyChanged("analysis_result_id");
					this.Onanalysis_result_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_live_table_lib_id", DbType="Decimal(18,0) NOT NULL")]
		public decimal live_table_lib_id
		{
			get
			{
				return this._live_table_lib_id;
			}
			set
			{
				if ((this._live_table_lib_id != value))
				{
					this.Onlive_table_lib_idChanging(value);
					this.SendPropertyChanging();
					this._live_table_lib_id = value;
					this.SendPropertyChanged("live_table_lib_id");
					this.Onlive_table_lib_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_result_tb_lib_id", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> result_tb_lib_id
		{
			get
			{
				return this._result_tb_lib_id;
			}
			set
			{
				if ((this._result_tb_lib_id != value))
				{
					this.Onresult_tb_lib_idChanging(value);
					this.SendPropertyChanging();
					this._result_tb_lib_id = value;
					this.SendPropertyChanged("result_tb_lib_id");
					this.Onresult_tb_lib_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pre_algorithm", DbType="NVarChar(20)")]
		public string pre_algorithm
		{
			get
			{
				return this._pre_algorithm;
			}
			set
			{
				if ((this._pre_algorithm != value))
				{
					this.Onpre_algorithmChanging(value);
					this.SendPropertyChanging();
					this._pre_algorithm = value;
					this.SendPropertyChanged("pre_algorithm");
					this.Onpre_algorithmChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pre_match_count", DbType="Int")]
		public System.Nullable<int> pre_match_count
		{
			get
			{
				return this._pre_match_count;
			}
			set
			{
				if ((this._pre_match_count != value))
				{
					this.Onpre_match_countChanging(value);
					this.SendPropertyChanging();
					this._pre_match_count = value;
					this.SendPropertyChanged("pre_match_count");
					this.Onpre_match_countChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_home_w", DbType="Int")]
		public System.Nullable<int> home_w
		{
			get
			{
				return this._home_w;
			}
			set
			{
				if ((this._home_w != value))
				{
					this.Onhome_wChanging(value);
					this.SendPropertyChanging();
					this._home_w = value;
					this.SendPropertyChanged("home_w");
					this.Onhome_wChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_home_d", DbType="Int")]
		public System.Nullable<int> home_d
		{
			get
			{
				return this._home_d;
			}
			set
			{
				if ((this._home_d != value))
				{
					this.Onhome_dChanging(value);
					this.SendPropertyChanging();
					this._home_d = value;
					this.SendPropertyChanged("home_d");
					this.Onhome_dChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_home_l", DbType="Int")]
		public System.Nullable<int> home_l
		{
			get
			{
				return this._home_l;
			}
			set
			{
				if ((this._home_l != value))
				{
					this.Onhome_lChanging(value);
					this.SendPropertyChanging();
					this._home_l = value;
					this.SendPropertyChanged("home_l");
					this.Onhome_lChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_home_goals", DbType="Float")]
		public System.Nullable<double> home_goals
		{
			get
			{
				return this._home_goals;
			}
			set
			{
				if ((this._home_goals != value))
				{
					this.Onhome_goalsChanging(value);
					this.SendPropertyChanging();
					this._home_goals = value;
					this.SendPropertyChanged("home_goals");
					this.Onhome_goalsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_away_goals", DbType="Float")]
		public System.Nullable<double> away_goals
		{
			get
			{
				return this._away_goals;
			}
			set
			{
				if ((this._away_goals != value))
				{
					this.Onaway_goalsChanging(value);
					this.SendPropertyChanging();
					this._away_goals = value;
					this.SendPropertyChanged("away_goals");
					this.Onaway_goalsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fit_win_loss", DbType="Float")]
		public System.Nullable<double> fit_win_loss
		{
			get
			{
				return this._fit_win_loss;
			}
			set
			{
				if ((this._fit_win_loss != value))
				{
					this.Onfit_win_lossChanging(value);
					this.SendPropertyChanging();
					this._fit_win_loss = value;
					this.SendPropertyChanged("fit_win_loss");
					this.Onfit_win_lossChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fit_goals", DbType="Float")]
		public System.Nullable<double> fit_goals
		{
			get
			{
				return this._fit_goals;
			}
			set
			{
				if ((this._fit_goals != value))
				{
					this.Onfit_goalsChanging(value);
					this.SendPropertyChanging();
					this._fit_goals = value;
					this.SendPropertyChanged("fit_goals");
					this.Onfit_goalsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fit_odd_even", DbType="Float")]
		public System.Nullable<double> fit_odd_even
		{
			get
			{
				return this._fit_odd_even;
			}
			set
			{
				if ((this._fit_odd_even != value))
				{
					this.Onfit_odd_evenChanging(value);
					this.SendPropertyChanging();
					this._fit_odd_even = value;
					this.SendPropertyChanged("fit_odd_even");
					this.Onfit_odd_evenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_result_fit", DbType="NVarChar(20)")]
		public string result_fit
		{
			get
			{
				return this._result_fit;
			}
			set
			{
				if ((this._result_fit != value))
				{
					this.Onresult_fitChanging(value);
					this.SendPropertyChanging();
					this._result_fit = value;
					this.SendPropertyChanged("result_fit");
					this.Onresult_fitChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_result_goals", DbType="NVarChar(20)")]
		public string result_goals
		{
			get
			{
				return this._result_goals;
			}
			set
			{
				if ((this._result_goals != value))
				{
					this.Onresult_goalsChanging(value);
					this.SendPropertyChanging();
					this._result_goals = value;
					this.SendPropertyChanged("result_goals");
					this.Onresult_goalsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_result_wdl", DbType="NVarChar(20)")]
		public string result_wdl
		{
			get
			{
				return this._result_wdl;
			}
			set
			{
				if ((this._result_wdl != value))
				{
					this.Onresult_wdlChanging(value);
					this.SendPropertyChanging();
					this._result_wdl = value;
					this.SendPropertyChanged("result_wdl");
					this.Onresult_wdlChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute()]
	public partial class match_table_xpath : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private decimal _uri_host_id;
		
		private string _uri_host;
		
		private string _max_table_xpath;
		
		private string _max_table_id_value;
		
		private string _second_table_xpath;
		
		private string _second_table_id_value;
		
		private System.Nullable<int> _order_table_id;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onuri_host_idChanging(decimal value);
    partial void Onuri_host_idChanged();
    partial void Onuri_hostChanging(string value);
    partial void Onuri_hostChanged();
    partial void Onmax_table_xpathChanging(string value);
    partial void Onmax_table_xpathChanged();
    partial void Onmax_table_id_valueChanging(string value);
    partial void Onmax_table_id_valueChanged();
    partial void Onsecond_table_xpathChanging(string value);
    partial void Onsecond_table_xpathChanged();
    partial void Onsecond_table_id_valueChanging(string value);
    partial void Onsecond_table_id_valueChanged();
    partial void Onorder_table_idChanging(System.Nullable<int> value);
    partial void Onorder_table_idChanged();
    #endregion
		
		public match_table_xpath()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_uri_host_id", DbType="Decimal(18,0) NOT NULL", IsPrimaryKey=true)]
		public decimal uri_host_id
		{
			get
			{
				return this._uri_host_id;
			}
			set
			{
				if ((this._uri_host_id != value))
				{
					this.Onuri_host_idChanging(value);
					this.SendPropertyChanging();
					this._uri_host_id = value;
					this.SendPropertyChanged("uri_host_id");
					this.Onuri_host_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_uri_host", DbType="NVarChar(500)")]
		public string uri_host
		{
			get
			{
				return this._uri_host;
			}
			set
			{
				if ((this._uri_host != value))
				{
					this.Onuri_hostChanging(value);
					this.SendPropertyChanging();
					this._uri_host = value;
					this.SendPropertyChanged("uri_host");
					this.Onuri_hostChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_max_table_xpath", DbType="NVarChar(500)")]
		public string max_table_xpath
		{
			get
			{
				return this._max_table_xpath;
			}
			set
			{
				if ((this._max_table_xpath != value))
				{
					this.Onmax_table_xpathChanging(value);
					this.SendPropertyChanging();
					this._max_table_xpath = value;
					this.SendPropertyChanged("max_table_xpath");
					this.Onmax_table_xpathChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_max_table_id_value", DbType="NVarChar(500)")]
		public string max_table_id_value
		{
			get
			{
				return this._max_table_id_value;
			}
			set
			{
				if ((this._max_table_id_value != value))
				{
					this.Onmax_table_id_valueChanging(value);
					this.SendPropertyChanging();
					this._max_table_id_value = value;
					this.SendPropertyChanged("max_table_id_value");
					this.Onmax_table_id_valueChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_second_table_xpath", DbType="NVarChar(500)")]
		public string second_table_xpath
		{
			get
			{
				return this._second_table_xpath;
			}
			set
			{
				if ((this._second_table_xpath != value))
				{
					this.Onsecond_table_xpathChanging(value);
					this.SendPropertyChanging();
					this._second_table_xpath = value;
					this.SendPropertyChanged("second_table_xpath");
					this.Onsecond_table_xpathChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_second_table_id_value", DbType="NVarChar(500)")]
		public string second_table_id_value
		{
			get
			{
				return this._second_table_id_value;
			}
			set
			{
				if ((this._second_table_id_value != value))
				{
					this.Onsecond_table_id_valueChanging(value);
					this.SendPropertyChanging();
					this._second_table_id_value = value;
					this.SendPropertyChanged("second_table_id_value");
					this.Onsecond_table_id_valueChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_order_table_id", DbType="Int")]
		public System.Nullable<int> order_table_id
		{
			get
			{
				return this._order_table_id;
			}
			set
			{
				if ((this._order_table_id != value))
				{
					this.Onorder_table_idChanging(value);
					this.SendPropertyChanging();
					this._order_table_id = value;
					this.SendPropertyChanged("order_table_id");
					this.Onorder_table_idChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute()]
	public partial class result_tb : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private decimal _result_tb_id;
		
		private string _html_position;
		
		private string _home_team_big;
		
		private string _away_team_big;
		
		private string _match_type;
		
		private string _s_date;
		
		private string _s_time;
		
		private string _home_team;
		
		private string _away_team;
		
		private string _full_time_score;
		
		private string _half_time_score;
		
		private string _odds;
		
		private string _win_loss_big;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onresult_tb_idChanging(decimal value);
    partial void Onresult_tb_idChanged();
    partial void Onhtml_positionChanging(string value);
    partial void Onhtml_positionChanged();
    partial void Onhome_team_bigChanging(string value);
    partial void Onhome_team_bigChanged();
    partial void Onaway_team_bigChanging(string value);
    partial void Onaway_team_bigChanged();
    partial void Onmatch_typeChanging(string value);
    partial void Onmatch_typeChanged();
    partial void Ons_dateChanging(string value);
    partial void Ons_dateChanged();
    partial void Ons_timeChanging(string value);
    partial void Ons_timeChanged();
    partial void Onhome_teamChanging(string value);
    partial void Onhome_teamChanged();
    partial void Onaway_teamChanging(string value);
    partial void Onaway_teamChanged();
    partial void Onfull_time_scoreChanging(string value);
    partial void Onfull_time_scoreChanged();
    partial void Onhalf_time_scoreChanging(string value);
    partial void Onhalf_time_scoreChanged();
    partial void OnoddsChanging(string value);
    partial void OnoddsChanged();
    partial void Onwin_loss_bigChanging(string value);
    partial void Onwin_loss_bigChanged();
    #endregion
		
		public result_tb()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_result_tb_id", DbType="Decimal(18,0) NOT NULL", IsPrimaryKey=true)]
		public decimal result_tb_id
		{
			get
			{
				return this._result_tb_id;
			}
			set
			{
				if ((this._result_tb_id != value))
				{
					this.Onresult_tb_idChanging(value);
					this.SendPropertyChanging();
					this._result_tb_id = value;
					this.SendPropertyChanged("result_tb_id");
					this.Onresult_tb_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_html_position", DbType="NVarChar(50)")]
		public string html_position
		{
			get
			{
				return this._html_position;
			}
			set
			{
				if ((this._html_position != value))
				{
					this.Onhtml_positionChanging(value);
					this.SendPropertyChanging();
					this._html_position = value;
					this.SendPropertyChanged("html_position");
					this.Onhtml_positionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_home_team_big", DbType="NVarChar(50)")]
		public string home_team_big
		{
			get
			{
				return this._home_team_big;
			}
			set
			{
				if ((this._home_team_big != value))
				{
					this.Onhome_team_bigChanging(value);
					this.SendPropertyChanging();
					this._home_team_big = value;
					this.SendPropertyChanged("home_team_big");
					this.Onhome_team_bigChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_away_team_big", DbType="NVarChar(50)")]
		public string away_team_big
		{
			get
			{
				return this._away_team_big;
			}
			set
			{
				if ((this._away_team_big != value))
				{
					this.Onaway_team_bigChanging(value);
					this.SendPropertyChanging();
					this._away_team_big = value;
					this.SendPropertyChanged("away_team_big");
					this.Onaway_team_bigChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_match_type", DbType="NVarChar(50)")]
		public string match_type
		{
			get
			{
				return this._match_type;
			}
			set
			{
				if ((this._match_type != value))
				{
					this.Onmatch_typeChanging(value);
					this.SendPropertyChanging();
					this._match_type = value;
					this.SendPropertyChanged("match_type");
					this.Onmatch_typeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_s_date", DbType="NVarChar(50)")]
		public string s_date
		{
			get
			{
				return this._s_date;
			}
			set
			{
				if ((this._s_date != value))
				{
					this.Ons_dateChanging(value);
					this.SendPropertyChanging();
					this._s_date = value;
					this.SendPropertyChanged("s_date");
					this.Ons_dateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_s_time", DbType="NVarChar(50)")]
		public string s_time
		{
			get
			{
				return this._s_time;
			}
			set
			{
				if ((this._s_time != value))
				{
					this.Ons_timeChanging(value);
					this.SendPropertyChanging();
					this._s_time = value;
					this.SendPropertyChanged("s_time");
					this.Ons_timeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_home_team", DbType="NVarChar(50)")]
		public string home_team
		{
			get
			{
				return this._home_team;
			}
			set
			{
				if ((this._home_team != value))
				{
					this.Onhome_teamChanging(value);
					this.SendPropertyChanging();
					this._home_team = value;
					this.SendPropertyChanged("home_team");
					this.Onhome_teamChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_away_team", DbType="NVarChar(50)")]
		public string away_team
		{
			get
			{
				return this._away_team;
			}
			set
			{
				if ((this._away_team != value))
				{
					this.Onaway_teamChanging(value);
					this.SendPropertyChanging();
					this._away_team = value;
					this.SendPropertyChanged("away_team");
					this.Onaway_teamChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_full_time_score", DbType="NVarChar(50)")]
		public string full_time_score
		{
			get
			{
				return this._full_time_score;
			}
			set
			{
				if ((this._full_time_score != value))
				{
					this.Onfull_time_scoreChanging(value);
					this.SendPropertyChanging();
					this._full_time_score = value;
					this.SendPropertyChanged("full_time_score");
					this.Onfull_time_scoreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_half_time_score", DbType="NVarChar(50)")]
		public string half_time_score
		{
			get
			{
				return this._half_time_score;
			}
			set
			{
				if ((this._half_time_score != value))
				{
					this.Onhalf_time_scoreChanging(value);
					this.SendPropertyChanging();
					this._half_time_score = value;
					this.SendPropertyChanged("half_time_score");
					this.Onhalf_time_scoreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_odds", DbType="NVarChar(50)")]
		public string odds
		{
			get
			{
				return this._odds;
			}
			set
			{
				if ((this._odds != value))
				{
					this.OnoddsChanging(value);
					this.SendPropertyChanging();
					this._odds = value;
					this.SendPropertyChanged("odds");
					this.OnoddsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_win_loss_big", DbType="NVarChar(50)")]
		public string win_loss_big
		{
			get
			{
				return this._win_loss_big;
			}
			set
			{
				if ((this._win_loss_big != value))
				{
					this.Onwin_loss_bigChanging(value);
					this.SendPropertyChanging();
					this._win_loss_big = value;
					this.SendPropertyChanged("win_loss_big");
					this.Onwin_loss_bigChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute()]
	public partial class result_tb_lib : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private decimal _result_tb_lib_id;
		
		private System.Nullable<int> _html_position;
		
		private System.Nullable<int> _home_team_big;
		
		private System.Nullable<int> _away_team_big;
		
		private string _match_type;
		
		private System.Nullable<System.DateTime> _match_time;
		
		private string _home_team;
		
		private string _away_team;
		
		private string _odds;
		
		private string _win_loss_big;
		
		private System.Nullable<int> _home_red_card;
		
		private System.Nullable<int> _away_red_card;
		
		private System.Nullable<int> _full_home_goals;
		
		private System.Nullable<int> _full_away_goals;
		
		private System.Nullable<int> _half_home_goals;
		
		private System.Nullable<int> _half_away_goals;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onresult_tb_lib_idChanging(decimal value);
    partial void Onresult_tb_lib_idChanged();
    partial void Onhtml_positionChanging(System.Nullable<int> value);
    partial void Onhtml_positionChanged();
    partial void Onhome_team_bigChanging(System.Nullable<int> value);
    partial void Onhome_team_bigChanged();
    partial void Onaway_team_bigChanging(System.Nullable<int> value);
    partial void Onaway_team_bigChanged();
    partial void Onmatch_typeChanging(string value);
    partial void Onmatch_typeChanged();
    partial void Onmatch_timeChanging(System.Nullable<System.DateTime> value);
    partial void Onmatch_timeChanged();
    partial void Onhome_teamChanging(string value);
    partial void Onhome_teamChanged();
    partial void Onaway_teamChanging(string value);
    partial void Onaway_teamChanged();
    partial void OnoddsChanging(string value);
    partial void OnoddsChanged();
    partial void Onwin_loss_bigChanging(string value);
    partial void Onwin_loss_bigChanged();
    partial void Onhome_red_cardChanging(System.Nullable<int> value);
    partial void Onhome_red_cardChanged();
    partial void Onaway_red_cardChanging(System.Nullable<int> value);
    partial void Onaway_red_cardChanged();
    partial void Onfull_home_goalsChanging(System.Nullable<int> value);
    partial void Onfull_home_goalsChanged();
    partial void Onfull_away_goalsChanging(System.Nullable<int> value);
    partial void Onfull_away_goalsChanged();
    partial void Onhalf_home_goalsChanging(System.Nullable<int> value);
    partial void Onhalf_home_goalsChanged();
    partial void Onhalf_away_goalsChanging(System.Nullable<int> value);
    partial void Onhalf_away_goalsChanged();
    #endregion
		
		public result_tb_lib()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_result_tb_lib_id", DbType="Decimal(18,0) NOT NULL", IsPrimaryKey=true)]
		public decimal result_tb_lib_id
		{
			get
			{
				return this._result_tb_lib_id;
			}
			set
			{
				if ((this._result_tb_lib_id != value))
				{
					this.Onresult_tb_lib_idChanging(value);
					this.SendPropertyChanging();
					this._result_tb_lib_id = value;
					this.SendPropertyChanged("result_tb_lib_id");
					this.Onresult_tb_lib_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_html_position", DbType="Int")]
		public System.Nullable<int> html_position
		{
			get
			{
				return this._html_position;
			}
			set
			{
				if ((this._html_position != value))
				{
					this.Onhtml_positionChanging(value);
					this.SendPropertyChanging();
					this._html_position = value;
					this.SendPropertyChanged("html_position");
					this.Onhtml_positionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_home_team_big", DbType="Int")]
		public System.Nullable<int> home_team_big
		{
			get
			{
				return this._home_team_big;
			}
			set
			{
				if ((this._home_team_big != value))
				{
					this.Onhome_team_bigChanging(value);
					this.SendPropertyChanging();
					this._home_team_big = value;
					this.SendPropertyChanged("home_team_big");
					this.Onhome_team_bigChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_away_team_big", DbType="Int")]
		public System.Nullable<int> away_team_big
		{
			get
			{
				return this._away_team_big;
			}
			set
			{
				if ((this._away_team_big != value))
				{
					this.Onaway_team_bigChanging(value);
					this.SendPropertyChanging();
					this._away_team_big = value;
					this.SendPropertyChanged("away_team_big");
					this.Onaway_team_bigChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_match_type", DbType="NVarChar(50)")]
		public string match_type
		{
			get
			{
				return this._match_type;
			}
			set
			{
				if ((this._match_type != value))
				{
					this.Onmatch_typeChanging(value);
					this.SendPropertyChanging();
					this._match_type = value;
					this.SendPropertyChanged("match_type");
					this.Onmatch_typeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_match_time", DbType="DateTime")]
		public System.Nullable<System.DateTime> match_time
		{
			get
			{
				return this._match_time;
			}
			set
			{
				if ((this._match_time != value))
				{
					this.Onmatch_timeChanging(value);
					this.SendPropertyChanging();
					this._match_time = value;
					this.SendPropertyChanged("match_time");
					this.Onmatch_timeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_home_team", DbType="NVarChar(50)")]
		public string home_team
		{
			get
			{
				return this._home_team;
			}
			set
			{
				if ((this._home_team != value))
				{
					this.Onhome_teamChanging(value);
					this.SendPropertyChanging();
					this._home_team = value;
					this.SendPropertyChanged("home_team");
					this.Onhome_teamChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_away_team", DbType="NVarChar(50)")]
		public string away_team
		{
			get
			{
				return this._away_team;
			}
			set
			{
				if ((this._away_team != value))
				{
					this.Onaway_teamChanging(value);
					this.SendPropertyChanging();
					this._away_team = value;
					this.SendPropertyChanged("away_team");
					this.Onaway_teamChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_odds", DbType="NVarChar(50)")]
		public string odds
		{
			get
			{
				return this._odds;
			}
			set
			{
				if ((this._odds != value))
				{
					this.OnoddsChanging(value);
					this.SendPropertyChanging();
					this._odds = value;
					this.SendPropertyChanged("odds");
					this.OnoddsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_win_loss_big", DbType="NVarChar(50)")]
		public string win_loss_big
		{
			get
			{
				return this._win_loss_big;
			}
			set
			{
				if ((this._win_loss_big != value))
				{
					this.Onwin_loss_bigChanging(value);
					this.SendPropertyChanging();
					this._win_loss_big = value;
					this.SendPropertyChanged("win_loss_big");
					this.Onwin_loss_bigChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_home_red_card", DbType="Int")]
		public System.Nullable<int> home_red_card
		{
			get
			{
				return this._home_red_card;
			}
			set
			{
				if ((this._home_red_card != value))
				{
					this.Onhome_red_cardChanging(value);
					this.SendPropertyChanging();
					this._home_red_card = value;
					this.SendPropertyChanged("home_red_card");
					this.Onhome_red_cardChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_away_red_card", DbType="Int")]
		public System.Nullable<int> away_red_card
		{
			get
			{
				return this._away_red_card;
			}
			set
			{
				if ((this._away_red_card != value))
				{
					this.Onaway_red_cardChanging(value);
					this.SendPropertyChanging();
					this._away_red_card = value;
					this.SendPropertyChanged("away_red_card");
					this.Onaway_red_cardChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_full_home_goals", DbType="Int")]
		public System.Nullable<int> full_home_goals
		{
			get
			{
				return this._full_home_goals;
			}
			set
			{
				if ((this._full_home_goals != value))
				{
					this.Onfull_home_goalsChanging(value);
					this.SendPropertyChanging();
					this._full_home_goals = value;
					this.SendPropertyChanged("full_home_goals");
					this.Onfull_home_goalsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_full_away_goals", DbType="Int")]
		public System.Nullable<int> full_away_goals
		{
			get
			{
				return this._full_away_goals;
			}
			set
			{
				if ((this._full_away_goals != value))
				{
					this.Onfull_away_goalsChanging(value);
					this.SendPropertyChanging();
					this._full_away_goals = value;
					this.SendPropertyChanged("full_away_goals");
					this.Onfull_away_goalsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_half_home_goals", DbType="Int")]
		public System.Nullable<int> half_home_goals
		{
			get
			{
				return this._half_home_goals;
			}
			set
			{
				if ((this._half_home_goals != value))
				{
					this.Onhalf_home_goalsChanging(value);
					this.SendPropertyChanging();
					this._half_home_goals = value;
					this.SendPropertyChanged("half_home_goals");
					this.Onhalf_home_goalsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_half_away_goals", DbType="Int")]
		public System.Nullable<int> half_away_goals
		{
			get
			{
				return this._half_away_goals;
			}
			set
			{
				if ((this._half_away_goals != value))
				{
					this.Onhalf_away_goalsChanging(value);
					this.SendPropertyChanging();
					this._half_away_goals = value;
					this.SendPropertyChanged("half_away_goals");
					this.Onhalf_away_goalsChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="tt")]
	public partial class Tt
	{
		
		private string _Tt1;
		
		public Tt()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="tt", Storage="_Tt1", DbType="NVarChar(100)")]
		public string Tt1
		{
			get
			{
				return this._Tt1;
			}
			set
			{
				if ((this._Tt1 != value))
				{
					this._Tt1 = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
